# Generated by Django 2.2.3 on 2019-07-10 11:16

from django.db import migrations, models


class Migration (migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel (
            name='Doctor',
            fields=[
                ('f_name', models.CharField (max_length=100)),
                ('l_name', models.CharField (max_length=100)),
                ('username', models.CharField (max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField (max_length=20)),
                ('email', models.EmailField (max_length=100)),
            ],
        ),
    ]
