# Generated by Django 2.0.7 on 2019-07-11 08:25

from django.conf import settings
from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        migrations.swappable_dependency (settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField (
            model_name='doctor',
            name='confirm_password',
            field=models.CharField (default='', max_length=20),
        ),
        migrations.AddField (
            model_name='doctor',
            name='user',
            field=models.ForeignKey (blank=True, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
